create TABLE IF NOT EXISTS `reader`(
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

create TABLE IF NOT EXISTS `book`(
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

create TABLE IF NOT EXISTS `author`(
)ENGINE=MyISAM DEFAULT CHARSET=utf8;
